import{a as b,S as v,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const w="52837655-6c21f27bf556d895abe6a0fd0",l=15,E=b.create({baseURL:"https://pixabay.com/api/",params:{key:w,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:l}});async function B(i,e=1){const{data:n}=await E.get("",{params:{q:i,page:e}});return n}const d=document.getElementById("gallery"),u=document.getElementById("load-more"),g=document.getElementById("loader"),M=new v(".gallery a",{captionsData:"alt",captionDelay:200});function I(i){const e=i.map(({webformatURL:n,largeImageURL:r,tags:t,likes:o,views:a,comments:y,downloads:L})=>`
<li class="photo-card">
  <a href="${r}">
    <img src="${n}" alt="${t}" loading="lazy" />
  </a>
  <div class="info">
    <div><b>Likes</b>${o}</div>
    <div><b>Views</b>${a}</div>
    <div><b>Comments</b>${y}</div>
    <div><b>Downloads</b>${L}</div>
  </div>
</li>`).join("");d.insertAdjacentHTML("beforeend",e),M.refresh()}function P(){d.innerHTML=""}function R(){g.classList.remove("is-hidden")}function f(){g.classList.add("is-hidden")}function $(){u.classList.remove("is-hidden")}function p(){u.classList.add("is-hidden")}const m={galleryEl:d,loadMoreBtn:u},H=document.querySelector(".form");let s={query:"",page:1,totalHits:0,isLoading:!1};H.addEventListener("submit",S);m.loadMoreBtn.addEventListener("click",q);async function S(i){i.preventDefault();const e=i.currentTarget.elements.search.value.trim();if(!e){c.warning({message:"Введіть слово для пошуку!",position:"topRight"});return}s={query:e,page:1,totalHits:0,isLoading:!1},P(),p(),await h()}async function q(){await h(!0)}async function h(i=!1){if(!s.isLoading){s.isLoading=!0,R();try{const{hits:e,totalHits:n}=await B(s.query,s.page);if(s.page===1&&n===0){c.info({message:"Нічого не знайдено. Спробуйте інше слово.",position:"topRight"}),f();return}I(e),s.page===1&&(s.totalHits=n,c.success({message:`Знайдено ${n} зображень.`,position:"topRight"})),s.page*l>=s.totalHits||e.length<l?(p(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$(),i&&e.length&&O(),s.page+=1}catch(e){c.error({message:"Помилка при завантаженні. Перевірте ключ API або інтернет.",position:"topRight"}),console.error(e)}finally{f(),s.isLoading=!1}}}function O(){const i=m.galleryEl.firstElementChild;if(!i)return;const{height:e}=i.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
