import{a as L,S as b,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v="52837655-6c21f27bf556d895abe6a0fd0",l=15,w=L.create({baseURL:"https://pixabay.com/api/",params:{key:v,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:l}});async function E(s,e=1){const{data:n}=await w.get("",{params:{q:s,page:e}});return n}const f=document.getElementById("gallery"),u=document.getElementById("load-more"),m=document.getElementById("loader"),B=new b(".gallery a",{captionsData:"alt",captionDelay:200});function M(s){const e=s.map(({webformatURL:n,largeImageURL:i,tags:t,likes:o,views:a,comments:p,downloads:y})=>`
<li class="photo-card">
  <a href="${i}">
    <img src="${n}" alt="${t}" loading="lazy" />
  </a>
  <div class="info">
    <div><b>Likes</b>${o}</div>
    <div><b>Views</b>${a}</div>
    <div><b>Comments</b>${p}</div>
    <div><b>Downloads</b>${y}</div>
  </div>
</li>`).join("");f.insertAdjacentHTML("beforeend",e),B.refresh()}function I(){f.innerHTML=""}function $(){m.classList.remove("is-hidden")}function H(){m.classList.add("is-hidden")}function P(){u.classList.remove("is-hidden")}function d(){u.classList.add("is-hidden")}const g={galleryEl:f,loadMoreBtn:u},O=document.getElementById("search-form");let r={query:"",page:1,totalHits:0,isLoading:!1};O.addEventListener("submit",S);g.loadMoreBtn.addEventListener("click",q);async function S(s){s.preventDefault();const e=s.currentTarget.elements.search.value.trim();if(!e){c.info({message:"Введіть слово для пошуку!"});return}r={query:e,page:1,totalHits:0,isLoading:!1},I(),d(),await h()}async function q(){await h(!0)}async function h(s=!1){if(!r.isLoading){r.isLoading=!0,$();try{const{totalHits:e,hits:n}=await E(r.query,r.page);if(r.page===1&&e===0){d(),c.warning({message:"Нічого не знайдено."});return}M(n),r.page===1&&(r.totalHits=e,c.success({message:`Знайдено ${e} зображень.`})),r.page*l>=r.totalHits||n.length<l?(d(),c.info({message:"We're sorry, but you've reached the end of search results."})):P(),s&&n.length&&x(),r.page+=1}catch(e){console.error(e),c.error({message:"Помилка запиту. Перевір ключ або мережу."})}finally{H(),r.isLoading=!1}}}function x(){const s=g.galleryEl.firstElementChild;if(!s)return;const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
